---
title: "Chapter 03-3"
author: "kangminji"
date: '2021 4 22 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 배열(행렬)

## 배열 생성
```{r}
x <- array(1:8, c(2,4))  # 2행 4열의 배열 생성
x
```

```{r}
y <- array(1:5,c(2,4))
y
```

```{r}
z <- array(1:24,c(4,3,2)) 
z 
z[3,2,2]    #19 꺼내기
z[4,3,1]    #12 꺼내기
```

Matrix(2차원 배열)
```{r}
matrix(1:12,nrow = 3)   # = array(1:12, c(3,4))
matrix(1:12, nrow = 3, byrow = T)
```

vector을 묶어서 array 생성
```{r}
v1 = 1:4
v2 = 5:8
v3 = 9:12
cbind(v1,v2,v3)    #열 단위로 묶어 배열 생성
rbind(v1,v2,v3)    #행 단위로 묶어 배열 생성

```

cbind,rbind는 2차원 배열
x,y도 2차원이므로 옆에 합쳐져서 나옴
```{r}
cbind(x,y)
rbind(x,y)
```

```{r}
x <- matrix(1:4, nrow=2)
y <- matrix(5:8, ncol=2)
x
y
x+y
```
## 배열 연산
element-wise +,-,*
```{r}
x+y
x-y
x*y
```

수학적인 행렬 곱(dot product)
```{r}
x %*% y
```
전치행렬(transpose)
```{r}
t(x)
```
역행렬
```{r}
x %*% solve(x)
```
행렬식(determinent)
```{r}
det(x)
```

## 배열에 유용한 함수
apply: 배열의 행 또는 열별로 함수 적용
```{r}
apply(x,1,mean)     #1: 행별로 적용
apply(x, 2, mean)   #2: 열별로 적용
apply(x,1,sum)
sum(x)
```
행과 열의 개수를 모두 출력
```{r}
dim(x)
```

sample: 벡터나 배열에서 샘플 추출
```{r}
a <- array(1:!2, c(3,4))
sample(a)
sample(a,4)
sample(a,4, prob = c(1:12))   #prob: 확률
```








