---
title: "조건문, 반복문"
author: "kangminji"
date: '2021 4 22 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 조건문

#### 1. []에 행/열 조건 명시
```{r}
test <- c(15, 20, 30, NA, 45) #na 선택
test
test[test<40 & !is.na(test)] #40이하, na 배제
test[test%%3==0 & !is.na(test)]  #3의 배수, na 배제
``` 
데이터프레임 응용
```{r}
df <- data.frame(name=c('길동','춘향','철수'),age=c(30,16,21),
                gender=factor(c('M','F','M')))
df
```
여성인 행만 추출
```{r}
df[df$gender=='F',]
```
25세 이상인 남성 행 추출
```{r}
df[df$age>25 & df$gender=='M',]
```
#### 2. if문
```{r}
x <- 5
if(x%%2 ==0) {
  print('짝수입니다.')
} else {
  print('홀수입니다.')
}
```

```{r}
if(x > 0) {
  print('양수')
} else if (x < 0) {
  print('음수')
} else {
  print('Zero')
}
```

```{r}
x <- 5
if(x > 1e-10) {                   #0.0000000001
  print('양수')
} else if (x < -1e-10) {          #-0.0000000001
  print('음수')
} else {
  print('Zero')
}
```

#### 3. ifelse 문

```{r}
score <- 75
pass <- ifelse(score>=60,'합격','불합격')
pass
```
students.csv파일 읽어서 학점 부여하기
```{r}
students <- read.csv('data/students.csv',fileEncoding = 'euc-kr')
students
options(digits=4)     #유효 숫자 자리수
apply(students[,2:4],1,mean)
students['평균'] = c(apply(students[,2:4], 1, mean))
students['평균']

students['학점'] = ifelse(students$평균>=90, 'A',
                        ifelse(students$평균>=80, 'B',
                               ifelse(students$평균>=70, 'C', 'D')))
students
```

