---
title: "function"
author: "kangminji"
date: '2021 4 23 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 함수
함수명 = function(전달인자1, 전달인자2, ...) {
함수 동작시 수행할 코드
return(반환값)
}
```{r}
fact <- function(x) {
  prod <- 1
  for(i in 1:x) {
    prod <- prod * i
  }
  return(prod)
}
factor(5)
factor(10)
```

정수 a~b의 합을 구하는 함수 range_sum
```{r}
range_sum <- function(a,b) {
  sum <- 0
  for (i in a:b) {
    sum <- sum + i
  }
  return(sum)
}
range_sum(1,10)
```

재귀함수: 자기가 자기를 호출
  n! = n * (n-1)! 
      (단, n=0일 때 1)
```{r}
facto <- function(n) {
  if (n == 0) {
    return(1)
  }
  return(n * factorial(n-1))
}
facto(10)
```

fibo(n) = fibo(n-1) + fibo(n-2)
    (단, n >= 2) 
    fibo(0) = 1, fibo(1) = 1,
```{r}
#1
fibo <- function(n) {
  if (n == 0 | n ==1) {
    return(1)                   #0이거나 1이면 1로 return
  }
  return(fibo(n-1) + fibo(n-2))
}
fibo(10)

#2
fibo <- function(n) {
  if (n < 2) {
    return(1)                   #2미만이면 1로 return
  }
  return(fibo(n-1) + fibo(n-2))
}
fibo(10)



fibo <- function(n) {
  if (n < 2) {
    return(1)                    #2미만이면 1로 return
  }
  return(fibo(n-1) + fibo(n-2))
}
for (i in 0:10) {
  print(paste(i, fibo(i)))
}
```

peak-to-peak 함수
```{r}
peak2peak <- function(x) {
  return(max(x)-min(x))
}
mat <- matrix(1:12, nrow = 3)
apply(mat, 1, mean)
mat
apply(mat, 1, peak2peak)      #행방향
apply(mat, 2, peak2peak)      #열방향
```
























