---
title: "Untitled"
author: "kangminji"
date: '2021 4 28 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

ggplot 산점도와 선 겹쳐그리기
```{r}
library(ggplot2)
library(dplyr)

ggplot(anscombe)+
  geom_point(aes(x1,y1), color='darkorange',size=3)+
  #scale_x_continuous(breaks = seq(2,20,2))+   #x축 그리드 설정
  #scale_y_continuous(breaks = seq(2,14,2))+
  xlim(2,20)+
  ylim(2,14)+
  geom_abline(intercept = 3, slope = 0.5,     
              color='cornflowerblue',size=1)
#scale을 정한다음 한계를 지정해줘야함.(순서)
#둘 중 하나만 써도 됨

p1 <- ggplot(anscombe)+
  geom_point(aes(x1,y1), color='darkorange',size=3)+
  scale_x_continuous(breaks = seq(2,20,2))+
  scale_y_continuous(breaks = seq(2,14,2))+
  xlim(2,20)+
  ylim(2,14)+
  geom_abline(intercept = 3, slope = 0.5,     #slope: 기울기, intercept: 절편
              color='cornflowerblue',size=1)+
  labs(title = 'Dataset 1')
p1
```
ggplot 그래프 여러개 붙이기
```{r}
#install.packages("gridExtra")
library(gridExtra)

p1 <- ggplot(anscombe)+
  geom_point(aes(x1,y1), color='darkorange',size=3)+
  scale_x_continuous(breaks = seq(2,20,2))+
  scale_y_continuous(breaks = seq(2,14,2))+
  xlim(2,20)+
  ylim(2,14)+
  geom_abline(intercept = 3, slope = 0.5,     #slope: 기울기, intercept: 절편
              color='cornflowerblue',size=1)+
  labs(title = 'Dataset 1')
p1
p2 <- ggplot(anscombe)+
  geom_point(aes(x2,y2), color='darkorange',size=3)+
  scale_x_continuous(breaks = seq(2,20,2))+
  scale_y_continuous(breaks = seq(2,14,2))+
  xlim(2,20)+
  ylim(2,14)+
  geom_abline(intercept = 3, slope = 0.5,     #slope: 기울기, intercept: 절편
              color='cornflowerblue',size=1)+
  labs(title = 'Dataset 2')
p3 <- ggplot(anscombe)+
  geom_point(aes(x3,y3), color='darkorange',size=3)+
  scale_x_continuous(breaks = seq(2,20,2))+
  scale_y_continuous(breaks = seq(2,14,2))+
  xlim(2,20)+
  ylim(2,14)+
  geom_abline(intercept = 3, slope = 0.5,     #slope: 기울기, intercept: 절편
              color='cornflowerblue',size=1)+
  labs(title = 'Dataset 3')
p4 <- ggplot(anscombe)+
  geom_point(aes(x4,y4), color='darkorange',size=3)+
  scale_x_continuous(breaks = seq(2,20,2))+
  scale_y_continuous(breaks = seq(2,14,2))+
  xlim(2,20)+
  ylim(2,14)+
  geom_abline(intercept = 3, slope = 0.5,     #slope: 기울기, intercept: 절편
              color='cornflowerblue',size=1)+
  labs(title = 'Dataset 4')

library(gridExtra)            #그림 여러개 붙여서 보여주기
grid.arrange(p1,p2,p3,p4, ncol=2, top="Anscombe's Quartet") 
```
plot 그래프 여러개 붙이기
```{r}

par(mfrow=c(1,1))
```

리스트 안에 다 넣어놓는 방법
```{r}
figures <- list()
figures <- append(figures, p1)
figures <- append(figures, p2)
figures <- append(figures, p3)
figures <- append(figures, p4)
figures
```
Source Rfactoring
```{r}

x <- ggplot(anscombe)+
  geom_point(aes(x4,y4),color='darkorange',size=3)
m1 <- x
#프로그램이 변수명을 만듦
assign(paste('m',4,sep='.'),x)
#새로 만든 변수 사용가능
grid.arrange(p1,p2,p3,m.4, ncol=2, top="Anscombe's Quartet") 
```

```{r}
#오류남
#m.1,2,3,4만듦

for(i in 1:4){
  x <- ggplot(anscombe)+
  geom_point(aes(anscombe[,i],anscombe[,i+4]), color='darkorange',size=3)+
  scale_x_continuous(breaks = seq(2,20,2))+
  scale_y_continuous(breaks = seq(2,14,2))+
  xlim(2,20)+
  ylim(2,14)+
  geom_abline(intercept = 3, slope = 0.5,     #slope: 기울기, intercept: 절편
              color='cornflowerblue',size=1)+
  labs(title = paste0('Dataset ',i),
       x=paste0('x',i),y=paste0('y',i))
  assign(paste('m',i,sep='.'),x)
}
anscombe[,1]  #x값
anscombe[,5]  #y값

grid.arrange(m.1,m.2,m.3,m.4, ncol=2, top="Anscombe's Quartet") 
```









