---
title: "chapter 06 exercise"
author: "kangminji"
date: '2021 4 27 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
p.221
```{r}
library(ggplot2)
library(dplyr)
library(gapminder)
```

####단원문제 
1. gapminder 데이터에 기록된 전 세계 인구의 구성비율은 어떻게 변화하고 있을까?
  1) 전체 관측 기간(1952~2007) 중 1952년도의 인구 구성을 추출한 후 [그림 6-25]와         같이 시각화 하라.
```{r}
x = gapminder %>% 
  filter(year == 1952) %>% 
  select(country, pop) %>%  # 나라만
  arrange(desc(pop)) %>% #gdp내림차순 순서대로
  head()
x
pie(x$pop,x$country)
```
  2) 1952~2007년의 인구 구성을 for문을 이용해 반복적으로 시각화하라.
```{r}
for (i in 1:length(unique(gapminder$year))){
  print(i)
  gap2 <- gapminder %>%
    filter(year==unique(gapminder$year)[i]) %>% 
    arrange(desc(pop)) %>% 
    head()
pie(gap2$pop/10000,gap2$country, main = unique(gapminder$year)[i] ) 
barplot(gap2$pop,names.arg=gap2$country, main = unique(gapminder$year)[i])
}

```

  3) 시각화 그래프를 통해 알게 된 사실을 몇 가지로 요약하라.


3. ggplot2를 이용하여 Iris 데이터 셋에 대해서 다음 문제를 푸세요.
   1) 품종별로 Sepal/Petal의 Length, Width 산점도 그리기. (총 6개)
```{r}
iris %>% names()
ggplot(iris,aes(Sepal.Length,Sepal.Width, col=Species))+
  geom_point(alpha=0.2)
ggplot(iris,aes(Sepal.Length,Petal.Length, col=Species))+
  geom_point(alpha=0.2)
ggplot(iris,aes(Sepal.Length,Petal.Width, col=Species))+
  geom_point(alpha=0.2)
ggplot(iris,aes(Sepal.Width,Petal.Length, col=Species))+
  geom_point(alpha=0.2)
ggplot(iris,aes(Sepal.Width,Petal.Width, col=Species))+
  geom_point(alpha=0.2)
ggplot(iris,aes(Petal.Length,Petal.Width, col=Species))+
  geom_point(alpha=0.2)
```
   
   2) 품종별 Sepal/Petal의 Length/Width 평균을 비교하되 항목을 옆으로 늘어놓은         것(beside=T)과 위로 쌓아올린 것 2개를 그리시오. 
      (총 12개 항목의 데이터를 2개의 그래프에)
```{r}
#1
a<- rbind(apply(iris[iris$Species=="setosa",c(1,2,3,4)],2,mean),
  apply(iris[iris$Species=="versicolor",c(1,2,3,4)],2,mean),
  apply(iris[iris$Species=="virginica",c(1,2,3,4)],2,mean))

barplot(a, beside = T,ylim=c(0,8))

barplot(a, beside=F,ylim=c(0,20))

#2
iris_df<- iris %>% 
  group_by(Species) %>% 
  summarise(mean_sL=mean(Sepal.Length),mean_sW=mean(Sepal.Width),mean_pL=mean(Petal.Length),mean_pW=mean(Petal.Width))
barplot(as.matrix(iris_df[,c(2,3,4,5)]),main="각 꽃의 평균 비교",
        beside=T, col=rainbow(nrow(iris_df)),ylim=c(0,8),)
legend('topright',legend = c("setosa","versicolor","virginica"),cex=0.8, fill=rainbow(nrow(iris_df)))

iris_df<- iris %>% 
  group_by(Species) %>% 
  summarise(mean_sL=mean(Sepal.Length),mean_sW=mean(Sepal.Width),mean_pL=mean(Petal.Length),mean_pW=mean(Petal.Width))
barplot(as.matrix(iris_df[,c(2,3,4,5)]),main="각 꽃의 평균 비교",
        beside=F, col=rainbow(nrow(iris_df)),ylim=c(0,20),)
legend('topright',legend = c("setosa","versicolor","virginica"),cex=0.8, fill=rainbow(nrow(iris_df)))
```

   3) 박스 플롯 그리기
```{r}
iris %>% boxplot()
```
   
   