---
title: "05. 데이터 가공"
author: "kangminji"
date: '2021 4 26 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Base R을 이용한 데이터 가공
```{r}
#install.packages("gapminder")
library(gapminder)
library(dplyr)
glimpse(gapminder)
```
각나라의 기대 수명(LifeExp)
```{r}
tail(gapminder[, c('country',"lifeExp")])
tail(gapminder[, c('country','lifeExp', 'year')])
```
샘플과 속성의 추출(filtering and selection)
```{r}
gapminder[1000:1009, c('country','lifeExp', 'year')]
gapminder[gapminder$country == 'Croatia',]
gapminder[gapminder$country == 'Croatia',c('year','pop')]
```

Croatia의 1990년도 이후의 연도, 기대수명과 인구
```{r}
gapminder[gapminder$country == 'Croatia' & gapminder$year >1990 ,c('year','lifeExp','pop')]
```
행/열 단위의 연산
```{r}
apply(gapminder[gapminder$country=='Croatia', c('lifeExp', 'pop')], 
      2, mean)   #apply: 1은 가로 2는 세로
```
CAGR: 연평균 증가율 
```{r}
gapminder[gapminder$country == 'Croatia',c('year','pop')]
(4493312/3882229)**(1/55)-1   #거의 늘어나지 않음

peak2peak = function(x) {
    return(max(x) - min(x))
}
apply(gapminder[gapminder$country=='Croatia', c('lifeExp', 'pop')], 
      2, peak2peak)
```





